name: Setup Branch Protection
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  protect:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Protect Branches
        uses: octokit/request-action@v2.x
        id: protect_branches
        with:
          route: PUT /repos/{repo}/branches/{branch}/protection
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          branch: main
          required_status_checks: null
          enforce_admins: true
          required_pull_request_reviews: true
          restrictions: null
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN_GITHUB }}
        
