name: Setup Branch Protection
on:
  push:
    branches:
      - main
permissions: write-all
jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Protect Branches
        run: |
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token  $Github_token" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "required_approving_review_count": 2
              },
            }'
            echo "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/branches/main/protection"
            echo "$Github_token "
    env: 
        Github_token: ${{ secrets.PERSONAL_TOKEN_GITHUB }}
